name: Laporan Bug / Bug Report
description: Laporkan bug yang bisa direproduksi di Dolanan Matematika / Report a reproducible bug in Dolanan Matematika
labels: [bug, needs-triage]
body:
  - type: markdown
    attributes:
      value: |
        Terima kasih sudah membantu meningkatkan Dolanan Matematika.
        Thank you for helping improve Dolanan Matematika.
  - type: textarea
    id: summary
    attributes:
      label: Ringkasan Bug / Bug Summary
      description: Apa yang terjadi? / What happened?
      placeholder: Deskripsi singkat bug / Short description of the bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Langkah Reproduksi / Steps to Reproduce
      description: Tuliskan langkah bernomor yang jelas. / Please provide clear numbered steps.
      placeholder: |
        1. Buka game ... / Open game ...
        2. Klik ... / Click ...
        3. Muncul error ... / See error ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Perilaku yang Diharapkan / Expected Behavior
      placeholder: Seharusnya apa yang terjadi? / What should happen instead?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Perilaku Aktual / Actual Behavior
      placeholder: Yang terjadi saat ini apa? / What happened instead?
    validations:
      required: true
  - type: dropdown
    id: game
    attributes:
      label: Permainan / Game
      options:
        - Rumah Penjumlahan
        - Rumah Perkalian
        - Both / Home screen
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: e.g. Chrome 122, Safari 18, Firefox 123
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Perangkat + OS / Device + OS
      placeholder: e.g. iPhone 13 / iOS 18, Windows 11 laptop
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot atau Rekaman Layar / Screenshots or Screen Recording
      description: Tarik-lepas gambar/video jika relevan. / Drag and drop images/video if relevant.
  - type: textarea
    id: console
    attributes:
      label: Error Console (opsional) / Console Errors (optional)
      description: Tempel error dari DevTools Console jika ada. / Paste errors from DevTools Console if available.
      render: shell
  - type: checkboxes
    id: checks
    attributes:
      label: Pengecekan Awal / Pre-check
      options:
        - label: Saya sudah mencari issue yang ada dan bug ini belum dilaporkan. / I have searched existing issues and this bug has not been reported yet.
          required: true
